//! Starter composition using only meshes generated by our own code.

use bevy::{app::AppExit, prelude::*};

use crate::{
    CharacterSystems,
    character::{Character, MovementIntent},
    controller::keyboard::{KeyboardController, KeyboardControllerPlugin},
};

pub struct SandboxPlugin;

impl Plugin for SandboxPlugin {
    fn build(&self, app: &mut App) {
        app.insert_resource(ClearColor(Color::srgb(0.035, 0.045, 0.07)))
            .add_plugins(KeyboardControllerPlugin)
            .add_systems(Startup, setup)
            .add_systems(FixedUpdate, move_body.in_set(CharacterSystems::Movement))
            .add_systems(Update, quit_on_escape);
    }
}

fn setup(
    mut commands: Commands,
    mut meshes: ResMut<Assets<Mesh>>,
    mut materials: ResMut<Assets<StandardMaterial>>,
) {
    commands.spawn((
        Name::new("Sandbox floor"),
        Mesh3d(meshes.add(Plane3d::default().mesh().size(20.0, 20.0))),
        MeshMaterial3d(materials.add(Color::srgb(0.12, 0.18, 0.23))),
    ));

    let character = commands
        .spawn((
            Name::new("Character body"),
            Character,
            MovementIntent::default(),
            Mesh3d(meshes.add(Capsule3d::default())),
            MeshMaterial3d(materials.add(Color::srgb(0.15, 0.85, 0.65))),
            Transform::from_xyz(0.0, 1.0, 0.0),
        ))
        .id();

    commands.spawn((
        Name::new("Keyboard controller"),
        KeyboardController {
            character,
            speed: 4.0,
        },
    ));

    commands.spawn((
        DirectionalLight {
            shadow_maps_enabled: true,
            ..default()
        },
        Transform::from_xyz(4.0, 8.0, 4.0).looking_at(Vec3::ZERO, Vec3::Y),
    ));

    commands.spawn((
        Camera3d::default(),
        Transform::from_xyz(0.0, 10.0, 14.0).looking_at(Vec3::new(0.0, 0.5, 0.0), Vec3::Y),
    ));

    commands.spawn((
        Text::new("Hello, Mashup!\nWASD / arrows: move   |   Esc: quit"),
        TextFont::from_font_size(24.0),
        TextColor(Color::WHITE),
        Node {
            position_type: PositionType::Absolute,
            top: px(20),
            left: px(24),
            ..default()
        },
    ));

    info!("Hello, Mashup! The sandbox uses procedural assets only.");
}

/// Demo-only kinematic movement. Replace this system with physics or specific
/// movement rules when composing another game; the character stays the same.
fn move_body(
    time: Res<Time<Fixed>>,
    mut characters: Query<(&MovementIntent, &mut Transform), With<Character>>,
) {
    for (intent, mut transform) in &mut characters {
        transform.translation += intent.velocity * time.delta_secs();
        transform.translation.x = transform.translation.x.clamp(-9.0, 9.0);
        transform.translation.z = transform.translation.z.clamp(-9.0, 9.0);
    }
}

fn quit_on_escape(keys: Res<ButtonInput<KeyCode>>, mut exit: MessageWriter<AppExit>) {
    if keys.just_pressed(KeyCode::Escape) {
        exit.write(AppExit::Success);
    }
}
